-- Create table 

CREATE TABLE public.countries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),          -- ID
  title text NOT NULL UNIQUE,                             -- Name of country
  
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid REFERENCES auth.users(id) ,
  updated_by uuid REFERENCES auth.users(id) 
);


-- Seed data

INSERT INTO public.countries (title) VALUES
  ('AFGHANISTAN'),
  ('ALBANIA'),
  ('ALGERIA'),
  ('ANDORRA'),
  ('ANGOLA'),
  ('ANTIGUA AND BARBUDA'),
  ('ARGENTINA'),
  ('ARMENIA'),
  ('AUSTRALIA'),
  ('AUSTRIA'),
  ('AZERBAIJAN'),
  ('BAHAMAS'),
  ('BAHRAIN'),
  ('BANGLADESH'),
  ('BARBADOS'),
  ('BELARUS'),
  ('BELGIUM'),
  ('BELIZE'),
  ('BENIN'),
  ('BHUTAN'),
  ('BOLIVIA'),
  ('BOSNIA AND HERZEGOVINA'),
  ('BOTSWANA'),
  ('BRAZIL'),
  ('BRUNEI'),
  ('BULGARIA'),
  ('BURKINA FASO'),
  ('BURUNDI'),
  ('CABO VERDE'),
  ('CAMBODIA'),
  ('CAMEROON'),
  ('CANADA'),
  ('CENTRAL AFRICAN REPUBLIC'),
  ('CHAD'),
  ('CHILE'),
  ('CHINA'),
  ('COLOMBIA'),
  ('COMOROS'),
  ('CONGO (BRAZZAVILLE)'),
  ('CONGO (KINSHASA)'),
  ('COSTA RICA'),
  ('CROATIA'),
  ('CUBA'),
  ('CYPRUS'),
  ('CZECHIA'),
  ('DENMARK'),
  ('DJIBOUTI'),
  ('DOMINICA'),
  ('DOMINICAN REPUBLIC'),
  ('ECUADOR'),
  ('EGYPT'),
  ('EL SALVADOR'),
  ('EQUATORIAL GUINEA'),
  ('ERITREA'),
  ('ESTONIA'),
  ('ESWATINI'),
  ('ETHIOPIA'),
  ('FIJI'),
  ('FINLAND'),
  ('FRANCE'),
  ('GABON'),
  ('GAMBIA'),
  ('GEORGIA'),
  ('GERMANY'),
  ('GHANA'),
  ('GREECE'),
  ('GRENADA'),
  ('GUATEMALA'),
  ('GUINEA'),
  ('GUINEA-BISSAU'),
  ('GUYANA'),
  ('HAITI'),
  ('HONDURAS'),
  ('HUNGARY'),
  ('ICELAND'),
  ('INDIA'),
  ('INDONESIA'),
  ('IRAN'),
  ('IRAQ'),
  ('IRELAND'),
  ('ISRAEL'),
  ('ITALY'),
  ('JAMAICA'),
  ('JAPAN'),
  ('JORDAN'),
  ('KAZAKHSTAN'),
  ('KENYA'),
  ('KIRIBATI'),
  ('KOREA, NORTH'),
  ('KOREA, SOUTH'),
  ('KOSOVO'),
  ('KUWAIT'),
  ('KYRGYZSTAN'),
  ('LAOS'),
  ('LATVIA'),
  ('LEBANON'),
  ('LESOTHO'),
  ('LIBERIA'),
  ('LIBYA'),
  ('LIECHTENSTEIN'),
  ('LITHUANIA'),
  ('LUXEMBOURG'),
  ('MADAGASCAR'),
  ('MALAWI'),
  ('MALAYSIA'),
  ('MALDIVES'),
  ('MALI'),
  ('MALTA'),
  ('MARSHALL ISLANDS'),
  ('MAURITANIA'),
  ('MAURITIUS'),
  ('MEXICO'),
  ('MICRONESIA'),
  ('MOLDOVA'),
  ('MONACO'),
  ('MONGOLIA'),
  ('MONTENEGRO'),
  ('MOROCCO'),
  ('MOZAMBIQUE'),
  ('MYANMAR'),
  ('NAMIBIA'),
  ('NAURU'),
  ('NEPAL'),
  ('NETHERLANDS'),
  ('NEW ZEALAND'),
  ('NICARAGUA'),
  ('NIGER'),
  ('NIGERIA'),
  ('NORTH MACEDONIA'),
  ('NORWAY'),
  ('OMAN'),
  ('PAKISTAN'),
  ('PALAU'),
  ('PALESTINE'),
  ('PANAMA'),
  ('PAPUA NEW GUINEA'),
  ('PARAGUAY'),
  ('PERU'),
  ('PHILIPPINES'),
  ('POLAND'),
  ('PORTUGAL'),
  ('QATAR'),
  ('ROMANIA'),
  ('RUSSIA'),
  ('RWANDA'),
  ('SAINT KITTS AND NEVIS'),
  ('SAINT LUCIA'),
  ('SAINT VINCENT AND THE GRENADINES'),
  ('SAMOA'),
  ('SAN MARINO'),
  ('SAO TOME AND PRINCIPE'),
  ('SAUDI ARABIA'),
  ('SENEGAL'),
  ('SERBIA'),
  ('SEYCHELLES'),
  ('SIERRA LEONE'),
  ('SINGAPORE'),
  ('SLOVAKIA'),
  ('SLOVENIA'),
  ('SOLOMON ISLANDS'),
  ('SOMALIA'),
  ('SOUTH AFRICA'),
  ('SOUTH SUDAN'),
  ('SPAIN'),
  ('SRI LANKA'),
  ('SUDAN'),
  ('SURINAME'),
  ('SWEDEN'),
  ('SWITZERLAND'),
  ('SYRIA'),
  ('TAIWAN'),
  ('TAJIKISTAN'),
  ('TANZANIA'),
  ('THAILAND'),
  ('TIMOR-LESTE'),
  ('TOGO'),
  ('TONGA'),
  ('TRINIDAD AND TOBAGO'),
  ('TUNISIA'),
  ('TURKEY'),
  ('TURKMENISTAN'),
  ('TUVALU'),
  ('UGANDA'),
  ('UKRAINE'),
  ('UNITED ARAB EMIRATES'),
  ('UNITED KINGDOM'),
  ('UNITED STATES'),
  ('URUGUAY'),
  ('UZBEKISTAN'),
  ('VANUATU'),
  ('VATICAN CITY'),
  ('VENEZUELA'),
  ('VIETNAM'),
  ('YEMEN'),
  ('ZAMBIA'),
  ('ZIMBABWE');
